### ISSUE TITLE
Sign out link show redirect to home page.

### ISSUE THREAD

**Issue by nichgalzin** [enBloc-org/arebyte-plugin-v4#49]
### Description of the Bug

Currently the sign out link keeps you on account page.

### What should happen instead

It should take you back to home screen

### Steps to reproduce this bug

na

### What could we do to solve this bug?

na

### Assignment

This issue is free for anyone to take

**Comment by ASANIYAN** [comment]
Hello. 
Can you assign this issue to me?

**Comment by camelPhonso** [comment]
This has been resolved as part of previous issue
